import { Fragment } from "react";
import { Box, Image, Button, Text } from "@chakra-ui/react";
import Head from "next/head";

type Props = {
  children: React.ReactNode;
};

export default function PageContainer({ children }: Props) {
  return (
    <Fragment>
      <Head>
        <title>Ternak Kode - Belajar ngoding terus, biar jago ngode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box
        bg="gray.800"
        py={8}
        as="header"
        borderColor="gray.600"
        alignItems="center"
      >
        <Image src="/logo.svg" width={300} mx="auto" py={4} mb={2} />
        <Box textAlign="center">
          <Text mb={6}>Ngoding terus, biar jago ngode.</Text>
          <Button
            as="a"
            href="https://www.instagram.com/ternak_kode/"
            target="_blank"
          >
            Join @ternak_kode
          </Button>
        </Box>
      </Box>
      <Box as="main" py={4} bg="gray.800">
        {children}
      </Box>
    </Fragment>
  );
}
