// pages/_document.js

import { Box, Button, ColorModeScript, Image, Text } from "@chakra-ui/react";
import NextDocument, { Html, Main, NextScript } from "next/document";
import theme from "./theme";
import Head from "next/head";

export default class Document extends NextDocument {
  render() {
    return (
      <Html lang="en">
        <Head>
          <title>Ternak Kode - Belajar ngoding terus, biar jago ngode</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <body>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
