import type { NextPage } from "next";
import Head from "next/head";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Fragment, useEffect, useState } from "react";
import ContentCard from "../components/ContentCard";
import { Box, Image, Button, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    (async () => {
      const resContent = await fetch(
        "https://sheets.googleapis.com/v4/spreadsheets/1vyaoL3cPm0ub2wOdszSASr6ItYDIHPb3a9Peay_ovfE/values/listContent?key=AIzaSyCt0PUL95MfEKFtYIStpPUs6iKbVLdGO9A"
      );
      const resContentDetail = await fetch(
        "https://sheets.googleapis.com/v4/spreadsheets/1vyaoL3cPm0ub2wOdszSASr6ItYDIHPb3a9Peay_ovfE/values/detailContent?key=AIzaSyCt0PUL95MfEKFtYIStpPUs6iKbVLdGO9A"
      );
      const contentDetail = (await resContentDetail.json()).values.map(
        (i: String[]) => ({
          key: i[0],
          img: i[1],
        })
      );

      const content = (await resContent.json()).values.map((i: String[]) => ({
        key: i[0],
        tag: i[1],
        publish_at: i[2],
        content: contentDetail.filter((ic: { key: String }) => ic.key === i[0]),
      }));

      setData(content);
    })();
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Ternak Kode - Belajar ngoding terus, biar jago ngode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box
        bg="gray.800"
        py={8}
        as="header"
        borderColor="gray.600"
        alignItems="center"
      >
        <Image src="/logo.svg" width={300} mx="auto" py={4} mb={2} />
        <Box textAlign="center">
          <Text mb={6}>Ngoding terus, biar jago ngode.</Text>
          <Button
            as="a"
            href="https://www.instagram.com/ternak_kode/"
            target="_blank"
          >
            Follow @ternak_kode
          </Button>
        </Box>
      </Box>
      <Box as="main" py={4}>
        {data.map((item, index) => (
          <ContentCard key={index} {...item} />
        ))}
      </Box>
    </Fragment>
  );
};

export default Home;
